HeadNode:
  LocalStorage:
    RootVolume:
      Size: 100
      Encrypted: false
      VolumeType: gp3
      Iops: 3000
      Throughput: 250
  CustomActions:
    OnNodeConfigured:
      Args:
        - 03.configure.slurm.acct.headnode.sh
        - 04.configure.slurm.AllOrNothing.headnode.sh
        - 07.configure.slurm.tagging.headnode.sh
        - 10.install.enginframe.headnode.sh
        - 12.configure.enginframe.alb.headnode.sh
        - 20.install.dcv.slurm.headnode.sh
        - 40.install.monitoring.headnode.sh
        - 50.install.capacity.reservation.pool.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
      - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      - Policy: arn:aws:iam::${AWS_ACCOUNT}:policy/${CLUSTER_NAME}-ODCR-Policy
    S3Access:
      - BucketName: '*'
        EnableWriteAccess: true
  InstanceType: c5.4xlarge
  Networking:
    AdditionalSecurityGroups:
      - ${ADDITIONAL_SG}
    ElasticIp: true
    SubnetId: ${SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  Imds:
    Secured: false
Image:
  Os: alinux2
DirectoryService:
  DomainName: dc=${DC0},dc=${DC1},dc=${DC2}
  DomainAddr: ldaps://${NLB_PUBLIC_DNS_NAME}
  PasswordSecretArn: ${SECRET_ARN}
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=Users,ou=${OU},dc=${DC0},dc=${DC1},dc=${DC2}
  LdapTlsReqCert: never
Region: ${AWS_REGION_NAME}
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
  SlurmQueues:
    - Name: compute-od-1
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: hpc6a-48xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: hpc6a.48xlarge
          MaxCount: 400
          MinCount: 0
        - Name: c5n-18xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c5n.18xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5n-24xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: r5n.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: compute-od-2
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: c5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: compute-od-3
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: c5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5d.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5d.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5d-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5d.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: compute-spot-1
      CapacityType: SPOT
      ComputeResources:
        - Name: c5n-18xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          InstanceType: c5n.18xlarge
          MaxCount: 300
          MinCount: 0
        - Name: c5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: c5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: m5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.24xlarge
          MaxCount: 300
          MinCount: 0
        - Name: r5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: r5.24xlarge
          MaxCount: 300
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: dcv-gpu
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: g4dn-xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-2xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.2xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-4xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.4xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-8xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.8xlarge
          MaxCount: 100
          MinCount: 0
        - Name: g4dn-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g4dn.16xlarge
          MaxCount: 100
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 25.install.dcv-server.gpu.sh
            - 26.configure.dcv.alb.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
    - Name: dcv
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: m5-24xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.24xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m5-2xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.2xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m5-8xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.8xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m5-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.16xlarge
          MaxCount: 200
          MinCount: 0
        - Name: m5-xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: m5.xlarge
          MaxCount: 200
          MinCount: 0
      CustomActions:
        OnNodeConfigured:
          Args:
            - 04.configure.disable.anacron.compute.sh
            - 25.install.dcv-server.compute.sh
            - 26.configure.dcv.alb.compute.sh
            - 40.install.monitoring.compute.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
          - Policy: arn:aws:iam::aws:policy/CloudWatchFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSPriceListServiceFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
          - Policy: arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      Networking:
        AdditionalSecurityGroups:
          - ${ADDITIONAL_SG}
        PlacementGroup:
          Enabled: true
        SubnetIds:
          - ${SUBNET_ID}
        AssignPublicIp: ${USE_PUBLIC_IPS}
SharedStorage:
${FSX}
Tags:
  - Key: EnginFrame
    Value: 'true'
  - Key: 1Click-HPC
    Value: 'true'
  - Key: 1Click-HPC-version
    Value: '0.4'